meilisearch:
  api_url: http://meilisearch:7700/
  api_key: ${MEILI_MASTER_KEY}
  insert_size: 1000
  insert_interval: 10

source:
  type: postgres
  host: ${POSTGRES_DEV_HOST}
  port: 5432
  database: ${POSTGRES_DEV_DATABASE}
  user: ${POSTGRES_DEV_USERNAME}
  password: ${POSTGRES_DEV_PASSWORD}

sync:
  - table: facility_pin
    index: facility_pin_index
    pk: id
    full: true

progress:
  type: file
  path: ./meili_data/meilisync/progress.json